config/routes.rb
Rails.application.routes.draw do
  resources :pics
  resources :cats
  get 'home/index'
  devise_for :users
  resources :comments, only: [:create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :pic
end

app/models/pic.rb
class Pic < ApplicationRecord
  has_many_attached :images
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @pic = Pic.find(params[:comment][:pic_id])
        @comment = Comment.new(comment_params)
        @comment.user = current_user
        respond_to do |format|
        if @comment.save
        format.html { redirect_to pic_path(@pic.id), notice:
        'Comment was successfully created.' }
        else
        format.html { redirect_to pic_path(@pic.id), notice:
        'Comment was not created.' }
        end
    end
    end
    private
    def comment_params
    params.require(:comment).permit(:content, :pic_id)
    end
        
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: %i[ show edit update destroy ]

  # GET /pics or /pics.json
  def index
    @pics = Pic.all
  end

  # GET /pics/1 or /pics/1.json
  def show
    @comment = Comment.new
  end

  # GET /pics/new
  def new
    @pic = Pic.new
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics or /pics.json
  def create
    @user = current_user
    @pic = @user.pics.build(pic_params)

    respond_to do |format|
      if @pic.save
        format.html { redirect_to pic_url(@pic), notice: "Pic was successfully created." }
        format.json { render :show, status: :created, location: @pic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1 or /pics/1.json
  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to pic_url(@pic), notice: "Pic was successfully updated." }
        format.json { render :show, status: :ok, location: @pic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1 or /pics/1.json
  def destroy
    @pic.destroy

    respond_to do |format|
      format.html { redirect_to pics_url, notice: "Pic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pic_params
      params.require(:pic).permit(:name, :description, :user_id, :images)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>
    <% if @comment.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este comentario no se pudo crear por las siguientes
            razones</h2>
            <ul>
                <% @comment.errors.full_messages.each do |msg|%>
                <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    <%= f.hidden_field :pic_id, value: @pic.id %>
    <div class = 'field'>
        <%= f.label :content, as: "Contenido" %>
        <%= f.text_field :content %>
    <div class = 'actions'>
        <%= f.submit %>
    </div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Karipic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pics/_form.html.erb
<%= form_with(model: pic) do |form| %>
  <% if pic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
        <% pic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :images, style: "display: block" %>
    <%= form.file_field :images, multiple: true %>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.hidden_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pics/_pic.html.erb
<div id="<%= dom_id pic %>">

  
  <p>
    <strong>Name:</strong>
    <%= pic.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= pic.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= pic.user.email %>
  </p>

</div>

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= render "form", pic: @pic %>

<br>

<div>
  <%= link_to "Show this pic", @pic %> |
  <%= link_to "Back to pics", pics_path %>
</div>

app/views/pics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pics</h1>

<div id="pics">
  <% @pics.each do |pic| %>
    <%= render pic %>
    <p>
      <%= link_to "Show this pic", pic %>
    </p>
  <% end %>
</div>

<%= link_to "New pic", new_pic_path %>

app/views/pics/new.html.erb
<h1>New pic</h1>

<%= render "form", pic: @pic %>

<br>

<div>
  <%= link_to "Back to pics", pics_path %>
</div>

app/views/pics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pic %>
<%= render 'comments/form'%>
<div>
  <%= link_to "Edit this pic", edit_pic_path(@pic) %> |
  <%= link_to "Back to pics", pics_path %>

  <%= button_to "Destroy this pic", @pic, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-dark border-bottom navbar-expand-lg border-bottom-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#">KariPic</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in?%>
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Fotos' , pics_path, class: 'nav-link text-white' %>
        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%if user_signed_in?%>
                <%= current_user.email%>
            <%else%>
                Dropdown
            <%end%>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Iniciar sesión' , new_user_session_path, class: 'nav-link' %></li>
            <li><%= link_to 'Registro' , new_user_registration_path, class: 'nav-link' %></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
                <%= button_to 'Cerrar sesión' , destroy_user_session_path, class: 'nav-link' , method:
                    :delete %>
            </li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>